### ISSUE TITLE
Content behind picker sticks to finger on iOS

### ISSUE THREAD

**Issue by roben** [TeamWertarbyte/material-ui-time-picker#12]
First of all thanks for the good work.

I have a minor issue when using this in a web app on iOS, though. When the time picker is open and you swipe on the clock to select a time, the main content of the page behind the picker still sticks to the finger and scrolls with it.  Everything still works, but it looks confusing ;) This does not happen on android, or at least not in the android SDK emulator.

**Comment by leMaik** [comment]
Thanks for reporting this. :+1: I'll have a look into this as soon as I have access to some iOS device.

**Comment by leMaik** [comment]
@roben This is fixed in v0.1.7

**Comment by roben** [comment]
Thanks!
