### ISSUE TITLE
How do I leave the value empty instead of the current time

### ISSUE THREAD

**Issue by barbarah** [TeamWertarbyte/material-ui-time-picker#14]
Nice timepicker!

If the value is empty the current time is displayed. Is it possible to show an empty input field instead of the current time? I tried to make the value `""`, `null` or `undefined`, but it always results in the current time instead of an empty field.

**Comment by RedHatter** [comment]
I would also like this feature.

**Comment by leMaik** [comment]
Good point, I'll add this.

**Comment by leMaik** [comment]
@mrmin123 A clear button could easily be added by the user, allowing much more customization.

**Comment by PorterK** [comment]
I believe PR #19 addresses this issue

**Comment by PorterK** [comment]
Although, what I did was slightly different than this feature request. I think a good solution is to have 2 different props like so: `defaultInputValue` and `defaultTime` this way they are both fully controllable / separated. @leMaik I can do this if you think its a better solution

**Comment by PorterK** [comment]
Updated PR #19 to address this issue specifically.

- Changes `defaultValue` to change _only_ the input value
- Adds an `initialTime` prop to change the `TimePicker` value
- Allows for null/undefined value for controlled inputs.

Anything I missed?
