### ISSUE TITLE
Update to Mui 1.0

### ISSUE THREAD

**Issue by JeSuis** [TeamWertarbyte/material-ui-time-picker#15]
Any plans to update this?
Its currently incompatible with the rc version of Mui
Mainly, imports have changed
I could help with this, but if wouldn't get merged I'll just fork it instead.

**Comment by leMaik** [comment]
We will update all our components in the coming weeks.

A PR would be great and will be merged for sure. :+1: 
(Why do you think it wouldn't get merged? This project is alive!)

**Comment by leMaik** [comment]
Working on this right now. :hourglass:

**Comment by leMaik** [comment]
[material-ui-time-picker v1.0.0](https://github.com/TeamWertarbyte/material-ui-time-picker/releases/tag/v1.0.0) supports Material-UI 1.0 :tada:

**Comment by JeSuis** [comment]
Thanks!
I had started on it but then ran into a problem with npm `prepare` and I didn't have time to update that
