### ISSUE TITLE
 Can't resolve '@material-ui/core/Button'

### ISSUE THREAD

**Issue by kapor190** [TeamWertarbyte/material-ui-time-picker#17]
Hello I try to integrate your TimeInput and I have got this error: 
./node_modules/material-ui-time-picker/lib/TimeInput.js
Module not found: Can't resolve '@material-ui/core/Button' in '..\node_modules\material-ui-time-picker\lib'

import TimeInput from 'material-ui-time-picker'

render () {
        const props = omit(this.props, [
            'className',
            'id',
        ])
        return (
            <div className={this.props.className} id={this.props.id}>
                <TimeInput
                    {...props}
                    mode='12h'
                    onChange={(time) => this.handleChange(time)}
                />
            </div>
        )
    }

React 16.4.1

**Comment by leMaik** [comment]
This component is only compatible with @material-ui/core 1.0.0 or later. It's _not_ compatible with earlier versions.
