### ISSUE TITLE
No release on merge?

### ISSUE THREAD

**Issue by PorterK** [TeamWertarbyte/material-ui-time-picker#21]
Hi. Looks like #19 and #20 got merged in to the repo but a new version was not released to NPM.

Tried to tag in PR #19 to ask about this but I think it was lost to notifs.

Can we get this released? Thanks! 👍

**Comment by leMaik** [comment]
I'm sorry. The release notes were already done, somehow I forgot to publish the package. :confused: 

v1.1.0 will be on npm shortly! :tada:
