### ISSUE TITLE
onChange return actual day instead value day 

### ISSUE THREAD

**Issue by rdelriods01** [TeamWertarbyte/material-ui-time-picker#23]
I use the timepicker for create events, so when I change the value of start/end time, it creates a new Date object instead of using the given date object value of my event. 

For example, let assume some things: 
   - Today is Wednesday 
   - startTime of my new event is <code>Sat Jan 19 2019 15:00:00 GMT -0600</code>
   - endTime of my new event is  <code>Sat Jan 19 2019 15:15:00 GMT -0600</code>

 so if I want to change the time of my endTime, to 15:30:00 it returns <code>Wed Jan 16 2019 15:30:00 GMT -0600</code> and I want to modify only hours and minutes, not the day.

To prevent that, I changed the next code in TimePicker.js

<pre>
  propagateChange = () => {
    if (this.props.onChange != null) {
      const date = new Date()
      date.setHours(this.state.hours)
      date.setMinutes(this.state.minutes)
      date.setSeconds(0)
      date.setMilliseconds(0)
      this.props.onChange(date)
    }
  }
</pre>

to 

<pre>
  propagateChange = () => {
    if (this.props.onChange != null) {
      const date = this.props.value // <-- Here
      date.setHours(this.state.hours)
      date.setMinutes(this.state.minutes)
      date.setSeconds(0)
      date.setMilliseconds(0)
      this.props.onChange(date)
    }
  }
</pre>

It would be nice if the team can check this issue or maybe it's just me, but if not please make a new commit with the changes.

**Comment by leMaik** [comment]
Hi @rdelriods01! This isn't _that_ trivial to fix. If we always take the future date, it would be impossible to select a time in the past. :wink: 

You should only take the _time_ part of our date. `onChange` only returns a `Date` instance for convenience. It's up to the user of this library (e.g. you) to select a proper date.

**Comment by leMaik** [comment]
Reopened; because we should at least have an example on how to do this without changing our code.

**Comment by rdelriods01** [comment]
but doing <code>const date = this.props.value</code> it will take the value given in the value prop, it doesn't matter if it's a past, present or future date, it will return the same day but different time or I'm wrong? 

And btw I changed my code and followed your recommendation and it works too. Here the example code:

```jsx

handleChange = (date) => {
    var minutes = date.getMinutes();
    var hours = date.getHours();
    var newDate = new Date(this.state.mydate);
    newDate.setHours(hours);
    newDate.setMinutes(minutes);
    this.setState({ mydate: newDate }, ()=> console.log(this.state)};
}


render() {
    return {
         <div>
           <TimeInput
             value={this.state.mydate}
             onChange={this.handleChange}
           />
        </div>
    }
}
```
