### ISSUE TITLE
Time Picker has its own state even if the value doesn't change

### ISSUE THREAD

**Issue by HarikiRito** [TeamWertarbyte/material-ui-time-picker#24]
TimePicker has its own value state instead of the value prop.

When the onChange function execute the `time.start` not change but the value in the component still change no matter what

Reproduce Behavior: [CodeSandBox reproduce](https://codesandbox.io/s/v3jm4k1oj0)

```jsx
<TimePicker value={time.start} mode="24h" onChange={onPickTimeStart} />
```

**Comment by leMaik** [comment]
@HarikiRito Sorry it took so long, but this is now fixed in [v1.2.0](https://github.com/TeamWertarbyte/material-ui-time-picker/releases/tag/v1.2.0).
