### ISSUE TITLE
Can't resolve '@date-io/date-fns'

### ISSUE THREAD

**Issue by tigpalmas** [TeamWertarbyte/material-ui-time-picker#25]
hi, i tried add the dependences 
 npm i -s material-ui-pickers 
npm i @date-io/date-fns date-fns@2.0.0-alpha.25
// or
npm i @date-io/moment moment
// or
npm i -s @date-io/luxon luxon
and still the error persist

**Comment by leMaik** [comment]
This is not `material-ui-pickers` but `material-ui-time-picker`. Please head over to their repository to ask them why this doesn't work. 😉
