### ISSUE TITLE
Doesn't pass the error prop down

### ISSUE THREAD

**Issue by michaloslav** [TeamWertarbyte/material-ui-time-picker#26]
Hey there, I've noticed that this component doesn't let me show an error the way you normally would with an Input component.

You should be able to easily fix this (as well as other issues some people might be having) by including `{...this.props}` or something like that in the Input element.

**Comment by leMaik** [comment]
We already do that: https://github.com/TeamWertarbyte/material-ui-time-picker/blob/master/src/TimeInput.js#L99

The `Input` doesn't have an error prop, though. You need to wrap it in a `FormControl`.

**Comment by michaloslav** [comment]
Oh thanks, didn't know that. Love the repo btw
