### ISSUE TITLE
How to set the color of the clock (timePicker) ?

### ISSUE THREAD

**Issue by IchrakMansour** [TeamWertarbyte/material-ui-time-picker#27]
I tried to change the color of the clock of timeInput (`material-ui-time-picker`) for the material-ui, but it's not changing.

My code is :

```
<TimeInput
        style ={heure}
        mode='24h'
        value={heureDebut}
        onChange={this.handleheureDChange}
        autoOk={true} 
        cancelLabel=""
        okLabel=""
        placeholder=""
        disableUnderline={true}  
        endAdornment={
            <InputAdornment position="end" style={{opacity:'0.4', marginLeft:'92px'}}>
            <IconButton><i style={{fontSize:'18px'}} className="zmdi zmdi-alarm" /></IconButton>
            </InputAdornment>
        }
/>
```
When I run it, I get :

![clock](https://user-images.githubusercontent.com/36265843/56194258-dafa9f80-6032-11e9-896f-656f4cb44054.PNG)

But I want the color blue will be changed to `#0E6EB8`

How can I change it?

**Comment by leMaik** [comment]
It uses the primary color from the theme, you can change it by customizing the theme as described here: https://material-ui.com/customization/themes/

Another way would be to change the styles by providing custom `classes`. That way, you can use any color. You'll have to set `classes={{ header: <your-header-class> }}` and the header class can then set the color.

**Comment by IchrakMansour** [comment]
@leMaik  I try that and it is not changed

**Comment by leMaik** [comment]
Having some code to look at would help a lot.

**Comment by leMaik** [comment]
It's been a while. Feel free to reopen this or raise a new issue if you need further help.
