### ISSUE TITLE
This doesn't look right...

### ISSUE THREAD

**Issue by AdityaAnand1** [TeamWertarbyte/material-ui-time-picker#3]
<img width="224" alt="screenshot 2017-10-17 16 43 31" src="https://user-images.githubusercontent.com/13274079/31662023-799bb3ae-b35a-11e7-8caf-32073bf86d4b.png">

```
<TimeInput mode="12h"  />
```

I'm on the latest chrome, 1920p, Windows.

**Comment by leMaik** [comment]
![image](http://www.reactiongifs.com/r/34fg.gif)

I'll look into this asap.

**Comment by leMaik** [comment]
This was caused by box-sizing being set to border-box on every element by an external CSS rule. Since this is pretty common, I fixed the time picker to work with any box-sizing.
