### ISSUE TITLE
Take the shortest route when moving the hand

### ISSUE THREAD

**Issue by AdityaAnand1** [TeamWertarbyte/material-ui-time-picker#5]
Steps to reproduce:

Open up the time picker, select, say 5 minutes. Then select like 55 minutes or something, the minute hand goes all the way around the clock along the clockwise route when it should be just a small hop away by going anti-clockwise.

Taking the short route would look much more subtle and pleasing from a UX standpoint, right now you can't even *feel* the ease-in-out interpolation, it's very in-your-face and kinda distracting and not very material-y 😄

**Comment by leMaik** [comment]
You are absolutely right and I'm really happy that someone other than me noticed this subtle glitch. :tada: 

I wasn't sure how to do this so I didn't and forgot about it. I'll look into this next weekend.

**Comment by leMaik** [comment]
@AdityaAnand1 This is now implemented in v0.1.4 :+1:
